package Classements;

public enum TypeClassements
{
	CLASSEMENT_SCRATCH,
	CLASSEMENT_AREVA,
	CLASSEMENT_ECOLES,
	CLASSEMENT_FEMMES,
	CLASSEMENT_MIXTES,
	CLASSEMENT_GRIMPEUR,
	CLASSEMENT_SPRINTEUR,
	CLASSEMENT_HOMMES,
	CLASSEMENT_ETUDIANT
}
