package ModeProgramme;

public enum ModesProgramme {
	MODE_DEFAULT,
	MODE_IMPORTATION,
	MODE_EQUIPES,
	MODE_AFFECTATION_DOIGTS,
	MODE_EQUIPESSANSPOINTAGES,
	MODE_CALCUL_CLASSEMENTS,
	MODE_LECTURE_POINTAGES,
	MODE_ACQUISITION_POINTAGES
}